#!/usr/bin/env python3
"""Builds assets/textures/atlas.png and src/voxel/atlas_tiles.rs from
textures/blocks.csv and the flat texture images under textures/.

blocks.csv is the single source of truth for the block roster: each row's
`texture`/`top`/`side`/`bottom` columns name a .png file (without extension)
directly under textures/; a blank top/side/bottom falls back to the row's
`texture` column. This script collects every distinct texture name the CSV
references, packs one 64x64 tile per name into a grid atlas, and emits a
generated Rust file with a `TILE_<NAME>` constant per texture plus a
`TILE_PLACEHOLDER` (textures/placeholder.png, used by block types that exist
outside the CSV roster) and `TILE_WHITE` (synthetic flat swatch, sampled by
entities that are tinted purely via per-vertex color).

Re-run after changing blocks.csv or any texture under textures/, then
`cargo build` to pick up the regenerated atlas_tiles.rs.
"""

import csv
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "textures"
CSV_PATH = RAW / "blocks.csv"
OUT_DIR = ROOT / "assets" / "textures"
ATLAS_OUT = OUT_DIR / "atlas.png"
RS_OUT = ROOT / "src" / "voxel" / "atlas_tiles.rs"

TILE = 64
COLS = 8


def load_tile(name: str) -> Image.Image:
    im = Image.open(RAW / f"{name}.png").convert("RGBA")
    if im.size != (TILE, TILE):
        im = im.resize((TILE, TILE), Image.LANCZOS)
    return im


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    names = set()
    with open(CSV_PATH, newline="") as f:
        for row in csv.DictReader(f):
            for col in ("texture", "top", "side", "bottom"):
                val = row[col].strip()
                if val:
                    names.add(val)
    names = sorted(names)

    tiles = [load_tile(n) for n in names]
    tile_names = list(names)

    placeholder = load_tile("placeholder")
    tiles.append(placeholder)
    tile_names.append("placeholder")

    white = Image.new("RGBA", (TILE, TILE), (255, 255, 255, 255))
    tiles.append(white)
    tile_names.append("white")

    rows = (len(tiles) + COLS - 1) // COLS
    atlas = Image.new("RGBA", (TILE * COLS, TILE * rows))
    for i, t in enumerate(tiles):
        col, row = i % COLS, i // COLS
        atlas.paste(t, (col * TILE, row * TILE))
    atlas.save(ATLAS_OUT)
    print(f"wrote {ATLAS_OUT} ({atlas.size[0]}x{atlas.size[1]}, {len(tiles)} tiles)")

    lines = [
        "// Generated by tools/build_atlas.py from textures/blocks.csv -- do not",
        "// edit by hand. Re-run the script after changing the CSV or textures.",
        "",
        f"pub const ATLAS_COLS: u32 = {COLS};",
        f"pub const ATLAS_ROWS: u32 = {rows};",
        "",
    ]
    for i, name in enumerate(tile_names):
        const_name = "TILE_" + name.upper()
        lines.append(f"pub const {const_name}: u8 = {i};")
    RS_OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {RS_OUT} ({len(tile_names)} tile constants)")


if __name__ == "__main__":
    main()
