#!/usr/bin/env python3
"""Generates World API documentation, Lua stubs, and Rust validation
metadata from world_api/schema.yaml (the single authoritative, machine-
readable World API description).

Outputs:
  - world_api/world_api_readme.md   full human-readable docs
  - world_api/world_api_compact.md  concise docs spliced into the LLM
                                     system prompt (prompts/system_prompt.txt)
  - world_api/world_api_stubs.lua   EmmyLua-style type stubs/autocomplete
  - src/world_api_gen.rs            Rust registry consumed by the
                                     pre-flight validator (src/world_api_validate.rs)

`block_kinds` isn't hardcoded in the schema -- it's derived here from
textures/blocks.csv (the block roster's own source of truth) plus the four
non-CSV extras, so this doc generator can't drift out of sync with the
actual block system.

Re-run after editing world_api/schema.yaml, then `cargo build`/`cargo test`.
"""

import csv
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = ROOT / "world_api" / "schema.yaml"
BLOCKS_CSV_PATH = ROOT / "textures" / "blocks.csv"
README_OUT = ROOT / "world_api" / "world_api_readme.md"
COMPACT_OUT = ROOT / "world_api" / "world_api_compact.md"
STUBS_OUT = ROOT / "world_api" / "world_api_stubs.lua"
RUST_OUT = ROOT / "src" / "world_api_gen.rs"

NON_CSV_BLOCK_EXTRAS = ["air", "mud", "redstone", "crystal", "campfire"]

LUA_TYPE = {
    "integer": "integer",
    "number": "number",
    "string": "string",
    "boolean": "boolean",
    "nil": "nil",
}


def block_kinds():
    with open(BLOCKS_CSV_PATH, newline="") as f:
        rows = list(csv.DictReader(f))
    ids = sorted(row["id"].strip().replace(" ", "_") for row in rows)
    return ids + NON_CSV_BLOCK_EXTRAS


def resolve_type(schema, types, t):
    """Expands a type reference (e.g. "PlayerSnapshot[]" or "X | nil") into
    a flat field list for docs, following `extends`. Returns None for a
    type name schema doesn't know about (plain scalar types)."""
    base = t.replace("[]", "").split(" | ")[0].strip()
    if base not in types:
        return None
    fields = list(types[base].get("fields", []))
    extends = types[base].get("extends")
    if extends:
        fields = resolve_type(schema, types, extends) + fields + types[base].get("adds", [])
    return fields


def fmt_field(f):
    desc = f" -- {f['desc']}" if f.get("desc") else ""
    enum = f" (one of: {', '.join(f['enum'])})" if f.get("enum") else ""
    return f"  - `{f['name']}` ({f['type']}){enum}{desc}"


def fmt_param_list(params):
    return ", ".join(p["name"] for p in params)


def fmt_param_docs(params):
    out = []
    for p in params:
        desc = f" -- {p['desc']}" if p.get("desc") else ""
        out.append(f"  - `{p['name']}` ({p['type']}){desc}")
    return out


def build_readme(schema, types, blocks):
    L = []
    L.append(f"# {schema['title']} (v{schema['version']})")
    L.append("")
    L.append(
        "> Generated by `tools/gen_world_api.py` from `world_api/schema.yaml` -- do not edit by hand."
    )
    L.append("")
    L.append(schema["description"].strip())
    L.append("")

    L.append("## Sandbox / engine")
    L.append("")
    eng = schema["engine"]
    L.append(f"- Runtime: {eng['runtime']}")
    L.append(f"- Tick interval: {eng['tick_interval_secs']}s (~{round(1/eng['tick_interval_secs'])}/sec)")
    L.append(f"- Allowed stdlib: {', '.join(eng['stdlib_allowed'])}")
    L.append(f"- Removed stdlib: {', '.join(eng['stdlib_removed'])} (never exist in this sandbox)")
    L.append(f"- Memory limit: {eng['memory_limit_bytes']:,} bytes")
    L.append(f"- Time budget: {eng['time_budget_ms']}ms per call (checked every {eng['instruction_hook_interval']} instructions)")
    L.append(f"- Instruction limit: {eng['instruction_limit']:,} per initialization/callback")
    L.append(f"- Source limit: {eng['source_limit_bytes']:,} UTF-8 bytes")
    L.append("")
    L.append(eng["execution_limits"].strip())
    L.append("")
    L.append(eng["scheduling"].strip())
    L.append("")
    L.append(eng["isolation"].strip())
    L.append("")
    L.append("## Callback transactions")
    L.append("")
    L.append(eng["transactions"].strip())
    L.append("")

    L.append("## Multiplayer authority")
    L.append("")
    L.append(schema["authority"].strip())
    L.append("")
    L.append("Replication channel per kind of effect:")
    L.append("")
    for k, v in schema["replication"].items():
        L.append(f"- **{k}**: {v}")
    L.append("")

    L.append("## Persistence")
    L.append("")
    p = schema["persistence"]
    L.append(f"- Saved fields: {', '.join(p['saved_fields'])}")
    L.append(f"- Save format: {p['save_format']}")
    L.append("")
    L.append(p["not_saved"].strip())
    L.append("")
    L.append(p["api_version_tagging"].strip())
    L.append("")

    L.append("## Budgets and limits")
    L.append("")
    for name, b in schema["budgets"].items():
        L.append(f"### `{name}` = {b['value']}")
        L.append(f"- Scope: {b.get('scope', 'global')}")
        L.append(f"- Applies to: {', '.join(f'`{m}`' for m in b['applies_to'])}")
        if b.get("on_exhausted"):
            L.append(f"- On exhausted: {b['on_exhausted']}")
        if b.get("on_exceeded"):
            L.append(f"- On exceeded: {b['on_exceeded']}")
        if b.get("note"):
            L.append(f"- Note: {b['note'].strip()}")
        L.append("")

    L.append("## Vocabularies")
    L.append("")
    L.append(f"- `creature_kinds`: {', '.join(schema['creature_kinds'])}")
    L.append(
        f"- `block_kinds` ({len(blocks)}, derived from `textures/blocks.csv` + {NON_CSV_BLOCK_EXTRAS}): "
        + ", ".join(f"`{b}`" for b in blocks)
    )
    L.append("")

    L.append("## Types")
    L.append("")
    for name, t in types.items():
        L.append(f"### `{name}`")
        if t.get("desc"):
            L.append(t["desc"])
        fields = resolve_type(schema, types, name)
        L.append("")
        for f in fields:
            L.append(fmt_field(f))
        L.append("")

    L.append("## Properties (`api.<name>`, read-only)")
    L.append("")
    for prop in schema["properties"]:
        L.append(f"### `api.{prop['name']}`: {prop['type']}")
        if prop.get("range"):
            L.append(f"- Range: {prop['range']}")
        if prop.get("enum"):
            L.append(f"- One of: {', '.join(prop['enum'])}")
        L.append(f"- {prop['desc']}")
        L.append("")

    for category, heading in [("query", "Query methods"), ("action", "Action methods")]:
        L.append(f"## {heading} (`api.<name>(...)`)")
        L.append("")
        for m in schema["methods"]:
            if m["category"] != category:
                continue
            sig = f"api.{m['name']}({fmt_param_list(m['params'])})"
            L.append(f"### `{sig}`")
            L.append(m["summary"])
            L.append("")
            if m["params"]:
                L.append("Parameters:")
                L.extend(fmt_param_docs(m["params"]))
                L.append("")
            L.append(f"Returns: `{m['returns']['type']}`" + (f" -- {m['returns']['desc']}" if m["returns"].get("desc") else ""))
            if m.get("budget_ref"):
                L.append(f"Budget: see `{m['budget_ref']}` above.")
            L.append("")

    L.append("## Events")
    L.append("")
    for e in schema["events"]:
        L.append(f"### `{e['signature']}`")
        L.append(f"- Required: {'yes' if e['required'] else 'no'}")
        if e.get("frequency"):
            L.append(f"- Frequency: {e['frequency']}")
        if e.get("event_type"):
            L.append(f"- `event` shape: `{e['event_type']}` (see Types above)")
        L.append(f"- {e['desc'].strip()}")
        L.append("")

    return "\n".join(L) + "\n"


def method_line(m):
    """One dense line per method: signature, summary, param/return caveats
    that matter (budget behavior, silent-failure/default semantics,
    asymmetries) -- the exact gotchas a small model is most likely to get
    wrong if they're dropped for brevity."""
    sig = f"api.{m['name']}({fmt_param_list(m['params'])})"
    parts = [f"- {sig}: {m['summary']}"]
    for p in m["params"]:
        if p.get("desc"):
            parts.append(f"{p['name']}: {p['desc']}")
    ret = m["returns"]
    ret_line = f"Returns {ret['type']}."
    if ret.get("desc"):
        ret_line += f" {ret['desc']}"
    parts.append(ret_line)
    return " ".join(parts)


def build_compact(schema, types, blocks):
    """Dense, low-token-count docs meant to be read by the local model doing
    rule generation -- same load-bearing gotchas as the readme, minus the
    surrounding prose."""
    L = []
    L.append(f"World API v{schema['version']} (the `api` table passed into on_tick/on_cast/on_death/on_block_break/on_interact)")
    L.append("")
    L.append(schema["engine"]["execution_limits"].strip())
    L.append(schema["engine"]["scheduling"].strip())
    L.append(f"World API spawns return nil at {schema['budgets']['creatures_max']['value']} live creatures (including starter creatures); destroying one frees capacity.")
    L.append(f"All API methods share {schema['budgets']['api_calls_per_invocation']['value']} calls per callback; exceeding this aborts execution. Coordinates must be within +/-{schema['budgets']['coordinate_abs_max']['value']} blocks; all numeric arguments must be finite f32 values.")
    L.append(schema["engine"]["transactions"].strip())
    L.append("")
    L.append("Queries:")
    for m in schema["methods"]:
        if m["category"] == "query":
            L.append(method_line(m))
    for prop in schema["properties"]:
        extra = f" One of: {', '.join(prop['enum'])}." if prop.get("enum") else ""
        L.append(f"- api.{prop['name']}: {prop['type']}. {prop['desc']}{extra}")
    L.append("")
    L.append(f"Table shapes -- {', '.join(types.keys())} (fields with a caveat noted inline):")
    for name, t in types.items():
        field_strs = []
        # A type that extends another (e.g. "X plus a distance field") is
        # shown as a delta against its base instead of repeating every
        # inherited field's full description again -- keeps token count down
        # without losing any information, since the base is listed too.
        fields = t.get("adds", []) if t.get("extends") else resolve_type(schema, types, name)
        for f in fields:
            if f.get("desc"):
                field_strs.append(f"{f['name']} [{f['desc']}]")
            else:
                field_strs.append(f["name"])
        if t.get("extends"):
            L.append(f"- {name} = {t['extends']} + {{{', '.join(field_strs)}}}")
        else:
            L.append(f"- {name} = {{{', '.join(field_strs)}}}")
    L.append("")
    L.append(
        f"Actions (budget-limited per call: {schema['budgets']['block_edits_per_call']['value']} block edits, "
        f"{schema['budgets']['creature_spawns_per_call']['value']} creature spawns -- an on_cast call gets higher budgets instead, "
        f"{schema['budgets']['block_edits_per_cast_call']['value']} block edits and {schema['budgets']['creature_spawns_per_cast_call']['value']} "
        f"creature spawns, since it runs once rather than ~10/sec; failures are silent -- check return values, not errors):"
    )
    for m in schema["methods"]:
        if m["category"] == "action":
            L.append(method_line(m))
    L.append("")
    L.append(f"Creature kinds: {', '.join(schema['creature_kinds'])}.")
    L.append(f"Block kinds ({len(blocks)}): {', '.join(blocks)}.")
    L.append("")
    for e in schema["events"]:
        req = "required" if e["required"] else "optional"
        L.append(f"{e['signature']} [{req}]: {e['desc'].strip()}")
    L.append("")
    L.append(schema["authority"].strip())
    return "\n".join(L) + "\n"


def build_stubs(schema, types, blocks):
    L = []
    L.append("---@meta world_api")
    L.append(f"-- World API v{schema['version']} type stubs, generated by tools/gen_world_api.py.")
    L.append("-- Do not edit by hand. For editor autocomplete (e.g. the VS Code/sumneko Lua extension):")
    L.append("-- point its workspace library path at this file's directory.")
    L.append("")
    for name, t in types.items():
        if t.get("extends"):
            L.append(f"---@class {name} : {t['extends']}")
            fields = t.get("adds", [])
        else:
            L.append(f"---@class {name}")
            fields = resolve_type(schema, types, name)
        for f in fields:
            L.append(f"---@field {f['name']} {LUA_TYPE.get(f['type'], f['type'])}")
        L.append("")
    L.append("---@class WorldApi")
    for prop in schema["properties"]:
        L.append(f"---@field {prop['name']} {LUA_TYPE.get(prop['type'], prop['type'])}")
    L.append("local api = {}")
    L.append("")
    for m in schema["methods"]:
        L.append(f"--- {m['summary']}")
        for p in m["params"]:
            L.append(f"---@param {p['name']} {LUA_TYPE.get(p['type'], p['type'])}" + (f" {p['desc']}" if p.get("desc") else ""))
        ret = m["returns"]["type"].replace(" | ", "|").replace("[]", "[]")
        L.append(f"---@return {ret}")
        L.append(f"function api.{m['name']}({fmt_param_list(m['params'])}) end")
        L.append("")
    L.append("--- Called ~10/sec while the module is enabled. Defines a RULE module.")
    L.append("--- Required unless the module defines on_cast instead (exactly one of the two).")
    L.append("---@param api WorldApi")
    L.append("function on_tick(api) end")
    L.append("")
    L.append("--- Runs once, immediately, when the host clicks Run. Defines an INSTANT SPELL")
    L.append("--- module instead of a RULE -- mutually exclusive with on_tick.")
    L.append("---@param api WorldApi")
    L.append("---@param event CastEvent")
    L.append("function on_cast(api, event) end")
    L.append("")
    L.append("--- Fires once per creature death. Optional.")
    L.append("---@param api WorldApi")
    L.append("---@param event DeathEvent")
    L.append("function on_death(api, event) end")
    L.append("")
    L.append("--- Fires once per real player-caused block break. Optional.")
    L.append("---@param api WorldApi")
    L.append("---@param event BlockBreakEvent")
    L.append("function on_block_break(api, event) end")
    L.append("")
    L.append("--- Fires once per real player-caused interact-key press (E), never changing")
    L.append("--- the block. Optional.")
    L.append("---@param api WorldApi")
    L.append("---@param event InteractEvent")
    L.append("function on_interact(api, event) end")
    L.append("")
    return "\n".join(L) + "\n"


def rust_str_list(items):
    return ", ".join(f'"{i}"' for i in items)


def build_rust(schema, blocks):
    method_names = [m["name"] for m in schema["methods"]]
    property_names = [p["name"] for p in schema["properties"]]
    L = []
    L.append("// Generated by tools/gen_world_api.py from world_api/schema.yaml -- do not")
    L.append("// edit by hand. Re-run the script after changing the schema.")
    L.append("//")
    L.append("// Consumed by src/world_api_validate.rs's pre-flight lint, which runs on")
    L.append("// LLM-generated Lua before it's ever loaded into a real Lua VM.")
    L.append("")
    L.append(f'pub const VERSION: &str = "{schema["version"]}";')
    L.append("")
    L.append("// Runtime execution limits, shared with the generated documentation.")
    for name, rust_type, value in [
        ("SCRIPT_TIME_MS", "u64", schema["engine"]["time_budget_ms"]),
        ("SCRIPT_INSTRUCTIONS", "u32", schema["engine"]["instruction_limit"]),
        ("SCRIPT_HOOK_INTERVAL", "u32", schema["engine"]["instruction_hook_interval"]),
        ("SCRIPT_MEMORY_BYTES", "usize", schema["engine"]["memory_limit_bytes"]),
        ("SCRIPT_SOURCE_BYTES", "usize", schema["engine"]["source_limit_bytes"]),
        ("SCRIPT_API_CALLS", "u32", schema["budgets"]["api_calls_per_invocation"]["value"]),
        ("SCRIPT_BROADCASTS", "u32", schema["budgets"]["broadcasts_per_invocation"]["value"]),
        ("SCRIPT_BROADCAST_BYTES", "usize", schema["budgets"]["broadcast_bytes_max"]["value"]),
        ("SCRIPT_COORDINATE_MAX", "i32", schema["budgets"]["coordinate_abs_max"]["value"]),
        ("SCRIPT_NATIVE_WORK", "u32", schema["budgets"]["native_work_per_invocation"]["value"]),
        ("SCRIPT_CREATURES_MAX", "usize", schema["budgets"]["creatures_max"]["value"]),
    ]:
        L.append(f"pub const {name}: {rust_type} = {value};")
    for name, rust_type, key in [
        ("DISPATCH_CALLBACKS", "usize", "callbacks_per_dispatch"),
        ("DISPATCH_TIME_MS", "u64", "time_ms"),
        ("DISPATCH_INSTRUCTIONS", "u32", "instructions"),
        ("DISPATCH_API_CALLS", "u32", "api_calls"),
        ("DISPATCH_NATIVE_WORK", "u32", "native_work"),
        ("PENDING_TOTAL", "usize", "pending_total"),
        ("PENDING_PER_MODULE", "usize", "pending_per_module"),
        ("SCRIPT_MODULES_MAX", "usize", "modules_max"),
    ]:
        L.append(f"pub const {name}: {rust_type} = {schema['engine']['scheduler'][key]};")
    L.append("")
    L.append("// Zero-based parameter positions used by native argument validation.")
    for registry, select in [
        ("NUMERIC_ARGUMENTS", lambda p: p["type"] in ("number", "integer")),
        ("COORDINATE_ARGUMENTS", lambda p: p["name"] in ("x", "y", "z", "cx", "cy", "cz", "x1", "y1", "z1", "x2", "y2", "z2")),
    ]:
        L.append(f"pub const {registry}: &[(&str, &[usize])] = &[")
        for method in schema["methods"]:
            indexes = [str(i) for i, param in enumerate(method["params"]) if select(param)]
            if indexes:
                L.append(f'    ("{method["name"]}", &[{", ".join(indexes)}]),')
        L.append("];")
        L.append("")
    L.append("/// Every `api.<name>` callable method this World API version defines.")
    L.append(f"pub const METHOD_NAMES: &[&str] = &[{rust_str_list(method_names)}];")
    L.append("")
    L.append("/// Every read-only `api.<name>` field (not callable) this version defines.")
    L.append(f"pub const PROPERTY_NAMES: &[&str] = &[{rust_str_list(property_names)}];")
    L.append("")
    L.append("/// Valid `kind` strings for a block (see get_block/replace_block/find_blocks),")
    L.append("/// derived from textures/blocks.csv plus the non-CSV extras.")
    L.append(f"pub const BLOCK_KINDS: &[&str] = &[{rust_str_list(blocks)}];")
    L.append("")
    L.append("/// Valid `kind` strings for a creature. Not read by the validator yet --")
    L.append("/// creature-kind typos already fail soft (silently default to \"sheep\", see")
    L.append("/// schema.yaml) rather than crash, so they're lower-value to flag than a bad")
    L.append("/// block kind -- but kept here for a future validator check or Lua stub use.")
    L.append("#[allow(dead_code)]")
    L.append(f"pub const CREATURE_KINDS: &[&str] = &[{rust_str_list(schema['creature_kinds'])}];")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    schema = yaml.safe_load(SCHEMA_PATH.read_text())
    types = schema["types"]
    blocks = block_kinds()

    README_OUT.write_text(build_readme(schema, types, blocks))
    print(f"wrote {README_OUT}")

    COMPACT_OUT.write_text(build_compact(schema, types, blocks))
    print(f"wrote {COMPACT_OUT}")

    STUBS_OUT.write_text(build_stubs(schema, types, blocks))
    print(f"wrote {STUBS_OUT}")

    RUST_OUT.write_text(build_rust(schema, blocks))
    print(f"wrote {RUST_OUT}")


if __name__ == "__main__":
    main()
