// Generated by tools/gen_world_api.py from world_api/schema.yaml -- do not
// edit by hand. Re-run the script after changing the schema.
//
// Consumed by src/world_api_validate.rs's pre-flight lint, which runs on
// LLM-generated Lua before it's ever loaded into a real Lua VM.

pub const VERSION: &str = "1.5.0";

/// Every `api.<name>` callable method this World API version defines.
pub const METHOD_NAMES: &[&str] = &["players", "nearest_player", "creatures", "find_creatures", "nearest_creature", "get_block", "find_blocks", "terrain_height", "distance", "chase", "damage", "destroy", "spawn_creature", "spawn_creature_near_player", "replace_block", "set_weather", "start_rain", "stop_rain", "set_time_of_day", "set_time_dawn", "set_time_night", "broadcast", "give_item", "take_item", "get_resource_count", "damage_player", "heal_player", "set_poisoned", "set_player_speed", "set_player_jump"];

/// Every read-only `api.<name>` field (not callable) this version defines.
pub const PROPERTY_NAMES: &[&str] = &["time_of_day", "is_night", "weather"];

/// Valid `kind` strings for a block (see get_block/replace_block/find_blocks),
/// derived from textures/blocks.csv plus the non-CSV extras.
pub const BLOCK_KINDS: &[&str] = &["basalt", "bedrock", "birch_leaves", "birch_wood", "bricks", "cherry_leaves", "cherry_wood", "cobblestone", "copper_ore", "diamond_ore", "emerald_ore", "gold_ore", "grass", "oak_leaves", "oak_wood", "pumpkin", "sand", "short_grass", "soil", "spruce_leaves", "spruce_wood", "stone", "water", "air", "mud", "redstone", "crystal"];

/// Valid `kind` strings for a creature. Not read by the validator yet --
/// creature-kind typos already fail soft (silently default to "sheep", see
/// schema.yaml) rather than crash, so they're lower-value to flag than a bad
/// block kind -- but kept here for a future validator check or Lua stub use.
#[allow(dead_code)]
pub const CREATURE_KINDS: &[&str] = &["sheep", "chicken", "stone_golem"];

