// Generated by tools/gen_world_api.py from world_api/schema.yaml -- do not
// edit by hand. Re-run the script after changing the schema.
//
// Consumed by src/world_api_validate.rs's pre-flight lint, which runs on
// LLM-generated Lua before it's ever loaded into a real Lua VM.

pub const VERSION: &str = "1.16.0";

// Runtime execution limits, shared with the generated documentation.
pub const SCRIPT_TIME_MS: u64 = 5;
pub const SCRIPT_INSTRUCTIONS: u32 = 100000;
pub const SCRIPT_HOOK_INTERVAL: u32 = 1000;
pub const SCRIPT_MEMORY_BYTES: usize = 8388608;
pub const SCRIPT_SOURCE_BYTES: usize = 65536;
pub const SCRIPT_API_CALLS: u32 = 512;
pub const SCRIPT_BROADCASTS: u32 = 8;
pub const SCRIPT_BROADCAST_BYTES: usize = 512;
pub const SCRIPT_COORDINATE_MAX: i32 = 1000000;
pub const SCRIPT_NATIVE_WORK: u32 = 65536;
pub const SCRIPT_CREATURES_MAX: usize = 256;
pub const DISPATCH_CALLBACKS: usize = 16;
pub const DISPATCH_TIME_MS: u64 = 20;
pub const DISPATCH_INSTRUCTIONS: u32 = 400000;
pub const DISPATCH_API_CALLS: u32 = 4096;
pub const DISPATCH_NATIVE_WORK: u32 = 262144;
pub const PENDING_TOTAL: usize = 512;
pub const PENDING_PER_MODULE: usize = 64;
pub const SCRIPT_MODULES_MAX: usize = 64;

// Zero-based parameter positions used by native argument validation.
pub const NUMERIC_ARGUMENTS: &[(&str, &[usize])] = &[
    ("nearest_player", &[0, 1, 2]),
    ("find_creatures", &[1, 2, 3, 4]),
    ("nearest_creature", &[1, 2, 3]),
    ("get_block", &[0, 1, 2]),
    ("find_blocks", &[1, 2, 3, 4]),
    ("terrain_height", &[0, 1]),
    ("distance", &[0, 1, 2, 3, 4, 5]),
    ("chase", &[0, 1, 2, 3]),
    ("protect_player", &[0]),
    ("suppress_creature_attacks", &[0]),
    ("get_behavior", &[0]),
    ("set_aggressive", &[0]),
    ("set_target", &[0, 2]),
    ("select_target", &[0, 2]),
    ("chase_target", &[0]),
    ("attack", &[0]),
    ("ignore", &[0]),
    ("die", &[0]),
    ("damage", &[0, 1]),
    ("destroy", &[0]),
    ("spawn_creature", &[1, 2, 3]),
    ("spawn_creature_near_player", &[0, 2]),
    ("replace_block", &[0, 1, 2]),
    ("set_time_of_day", &[0]),
    ("give_item", &[0, 2]),
    ("take_item", &[0, 2]),
    ("get_resource_count", &[0]),
    ("get_inventory", &[0]),
    ("has_resource", &[0, 2]),
    ("has_item", &[0, 2]),
    ("damage_player", &[0, 1]),
    ("heal_player", &[0, 1]),
    ("set_poisoned", &[0]),
    ("set_player_speed", &[0, 1]),
    ("set_player_jump", &[0, 1]),
    ("teleport_player", &[0, 1, 2, 3]),
];

pub const COORDINATE_ARGUMENTS: &[(&str, &[usize])] = &[
    ("nearest_player", &[0, 1, 2]),
    ("find_creatures", &[1, 2, 3]),
    ("nearest_creature", &[1, 2, 3]),
    ("get_block", &[0, 1, 2]),
    ("find_blocks", &[1, 2, 3]),
    ("terrain_height", &[0, 1]),
    ("distance", &[0, 1, 2, 3, 4, 5]),
    ("chase", &[1, 2, 3]),
    ("spawn_creature", &[1, 2, 3]),
    ("replace_block", &[0, 1, 2]),
    ("teleport_player", &[1, 2, 3]),
];

/// Every `api.<name>` callable method this World API version defines.
pub const METHOD_NAMES: &[&str] = &["players", "nearest_player", "creatures", "find_creatures", "nearest_creature", "get_block", "find_blocks", "terrain_height", "distance", "chase", "protect_player", "suppress_creature_attacks", "get_behavior", "set_aggressive", "set_target", "select_target", "chase_target", "attack", "ignore", "die", "damage", "destroy", "spawn_creature", "spawn_creature_near_player", "replace_block", "set_weather", "start_rain", "stop_rain", "set_time_of_day", "set_time_dawn", "set_time_night", "broadcast", "give_item", "take_item", "get_resource_count", "get_inventory", "has_resource", "has_item", "damage_player", "heal_player", "set_poisoned", "set_player_speed", "set_player_jump", "teleport_player"];

/// Every read-only `api.<name>` field (not callable) this version defines.
pub const PROPERTY_NAMES: &[&str] = &["time_of_day", "is_night", "weather"];

/// Valid `kind` strings for a block (see get_block/replace_block/find_blocks),
/// derived from textures/blocks.csv plus the non-CSV extras.
pub const BLOCK_KINDS: &[&str] = &["amber", "amethyst", "ash", "basalt", "bedrock", "birch_leaves", "birch_wood", "bluebell", "bricks", "bronze", "brown_mushroom", "cattail", "ceramic", "charcoal", "cherry_leaves", "cherry_wood", "clay", "cloth", "clover", "coal", "cobblestone", "copper", "copper_ore", "crystal_dust", "diamond", "diamond_ore", "dry_shrub", "emerald", "emerald_ore", "enchanted_glass", "fern", "flax", "glass", "glowcap", "gold", "gold_ore", "granite", "grass", "iron", "iron_ore", "lavender", "lime", "limestone", "marble", "mithril", "mithril_ore", "moon_silver", "moonstone", "mortar", "oak_leaves", "oak_wood", "obsidian", "peat", "planks", "plant_fiber", "pumpkin", "quartz", "red_poppy", "reeds", "resin", "rock_salt", "ruby", "ruby_ore", "runestone", "sand", "sapphire", "sapphire_ore", "short_grass", "silver", "silver_ore", "snow", "soil", "spruce_leaves", "spruce_wood", "steel", "stone", "sulfur", "thorn_bush", "tin", "tin_ore", "water", "wild_herbs", "wood_pulp", "air", "mud", "redstone", "crystal"];

/// Valid `kind` strings for a creature. Not read by the validator yet --
/// creature-kind typos already fail soft (silently default to "sheep", see
/// schema.yaml) rather than crash, so they're lower-value to flag than a bad
/// block kind -- but kept here for a future validator check or Lua stub use.
#[allow(dead_code)]
pub const CREATURE_KINDS: &[&str] = &["sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch"];

