---@meta world_api
-- World API v1.13.0 type stubs, generated by tools/gen_world_api.py.
-- Do not edit by hand. For editor autocomplete (e.g. the VS Code/sumneko Lua extension):
-- point its workspace library path at this file's directory.

---@class PlayerSnapshot
---@field id integer
---@field x number
---@field y number
---@field z number
---@field carrying_crystal boolean
---@field speed number
---@field vertical_speed number
---@field on_ground boolean
---@field running boolean
---@field in_water boolean
---@field health number
---@field poisoned boolean
---@field speed_multiplier number
---@field jump_multiplier number
---@field oxygen number

---@class PlayerSnapshotWithDistance : PlayerSnapshot
---@field distance number

---@class CreatureSnapshot
---@field id integer
---@field kind string
---@field x number
---@field y number
---@field z number
---@field health number
---@field max_health number

---@class CreatureSnapshotWithDistance : CreatureSnapshot
---@field distance number

---@class BlockPos
---@field x integer
---@field y integer
---@field z integer

---@class CastEvent
---@field player_id integer

---@class DeathEvent
---@field kind string
---@field x number
---@field y number
---@field z number

---@class BlockBreakEvent
---@field kind string
---@field x integer
---@field y integer
---@field z integer
---@field player_id integer

---@class InteractEvent
---@field kind string
---@field x integer
---@field y integer
---@field z integer
---@field player_id integer

---@class WorldApi
---@field time_of_day number
---@field is_night boolean
---@field weather string
local api = {}

--- Every connected player.
---@return PlayerSnapshot[]
function api.players() end

--- The single closest connected player to a point. Prefer this over looping players() yourself when you just need the closest one.
---@param x number
---@param y number
---@param z number
---@return PlayerSnapshotWithDistance|nil
function api.nearest_player(x, y, z) end

--- Every creature in the world.
---@return CreatureSnapshot[]
function api.creatures() end

--- Creatures of one kind within a radius of a point.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch", or "any". An unrecognized string is treated the same as "any" -- it is NOT an error, so a typo silently matches every creature instead of failing loudly.
---@param cx number
---@param cy number
---@param cz number
---@param radius number Clamped into [0, find_radius_max].
---@return CreatureSnapshot[]
function api.find_creatures(kind, cx, cy, cz, radius) end

--- The single closest creature of one kind to a point. No radius argument -- it searches every creature in the world unconditionally.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch", or "any" -- same unrecognized-string-means-any behavior as find_creatures.
---@param x number
---@param y number
---@param z number
---@return CreatureSnapshotWithDistance|nil
function api.nearest_creature(kind, x, y, z) end

--- The block at an integer position.
---@param x integer
---@param y integer
---@param z integer
---@return string
function api.get_block(x, y, z) end

--- Positions of every block of one kind within a radius of a point.
---@param kind string A block id from block_kinds, OR the special category alias "wood" (matches any tree species: oak_wood, spruce_wood, birch_wood, cherry_wood). Unlike find_creatures' kind, an unrecognized string here returns an EMPTY result, not "match everything" -- this asymmetry is a real gotcha, not a design you can rely on being consistent across query methods.
---@param cx integer
---@param cy integer
---@param cz integer
---@param radius number Clamped into [0, find_radius_max].
---@return BlockPos[]
function api.find_blocks(kind, cx, cy, cz, radius) end

--- The integer y of the topmost solid ground block at a column. Useful for placing/spawning things at the correct height instead of guessing.
---@param x integer
---@param z integer
---@return integer
function api.terrain_height(x, z) end

--- Straight-line distance between two points. Prefer this over writing your own sqrt(dx*dx+dy*dy+dz*dz).
---@param x1 number
---@param y1 number
---@param z1 number
---@param x2 number
---@param y2 number
---@param z2 number
---@return number
function api.distance(x1, y1, z1, x2, y2, z2) end

--- Makes a creature move toward a point at increased speed. Call it again every tick to keep it chasing -- stop calling it and the creature reverts to normal wandering within about a third of a second (there is no separate "stop chasing" call).
---@param creature_id integer
---@param x number
---@param y number
---@param z number
---@return nil
function api.chase(creature_id, x, y, z) end

--- Reduces a creature's health. Fires on_death (to every module, not just the caller) if this brings health to zero or below, and despawns it.
---@param creature_id integer
---@param amount number
---@return nil
function api.damage(creature_id, amount) end

--- Removes a creature immediately regardless of remaining health, and fires on_death.
---@param creature_id integer
---@return nil
function api.destroy(creature_id) end

--- Spawns a new creature at a position. sheep/chicken/cow are passive (only ever move under a rule's chase, never attack). stone_golem, wolf, stinger, goblin, and sunscorch are different: all five hostile entirely on their own, with no Lua involved -- each closes on and periodically damages the nearest player within its own aggro radius. stone_golem is large, slow, and hits hardest on the longest cooldown; sunscorch is a rare, tanky ghost that never gives up a chase and (like stone_golem) never speeds up while chasing -- no run animation, mechanically identical pace whether wandering or aggroed; goblin is a mid-weight melee bruiser (moderate speed/damage/cooldown, tankier than wolf); wolf is faster and lighter; stinger is fastest to attack (shortest cooldown) but hits lightest and is the most fragile. Only spawn a hostile one when a hostile/dangerous creature is actually what the request wants.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", or "sunscorch"; anything else (including a typo) silently becomes "sheep" -- not an error.
---@param x number
---@param y number
---@param z number
---@return integer|nil
function api.spawn_creature(kind, x, y, z) end

--- Spawns a new creature at a random point within radius blocks of a player (horizontally; height snaps to terrain). Prefer this over spawn_creature plus your own random offset when the rule is about spawning near a specific player.
---@param player_id integer
---@param kind string Same silent-default-to-sheep behavior as spawn_creature.
---@param radius number Clamped into [1, find_radius_max] -- note the floor is 1, not 0, unlike the find_* methods.
---@return integer|nil
function api.spawn_creature_near_player(player_id, kind, radius) end

--- Changes one block.
---@param x integer
---@param y integer
---@param z integer
---@param kind string A block id from block_kinds (e.g. "air" to clear a block).
---@return boolean
function api.replace_block(x, y, z, kind) end

--- Sets the weather directly, and resets the engine's own random weather timer (so it won't immediately pick something else out from under you).
---@param name string "clear" is also accepted, as an alias for "sunny" (its name before the 5-weather system existed).
---@return nil
function api.set_weather(name) end

--- Shorthand for set_weather("rain").
---@return nil
function api.start_rain() end

--- Shorthand for set_weather("sunny").
---@return nil
function api.stop_rain() end

--- Sets the time of day directly.
---@param t number Wrapped into [0,1) (e.g. -0.25 and 1.25 both become 0.75), same scale as api.time_of_day.
---@return nil
function api.set_time_of_day(t) end

--- Shorthand for set_time_of_day(0.0).
---@return nil
function api.set_time_dawn() end

--- Shorthand for set_time_of_day(0.5) -- sunset, night begins.
---@return nil
function api.set_time_night() end

--- Queues a notification and server log message, emitted only if the callback commits. At most 8 messages per callback, each at most 512 UTF-8 bytes; exceeding either limit aborts execution with an uncatchable budget failure.
---@param message string
---@return nil
function api.broadcast(message) end

--- Grants items straight into a player's Resources inventory (the panel populated by hand-gathering blocks), bypassing the world entirely. Only use this when the request explicitly asks to add to a player's inventory/resources -- for everything else ("add 100 stone", "fill this area with water"), prefer replace_block to place blocks in the world instead.
---@param player_id integer Target player (matches PlayerSnapshot.id).
---@param kind string A block id from block_kinds, but only the ones gatherable by hand (a resource, not e.g. "air" or "water") count -- anything else is rejected.
---@param amount integer Clamped into [0, item_grant_max].
---@return boolean
function api.give_item(player_id, kind, amount) end

--- Removes items from a player's Resources inventory -- the reverse of give_item. ONLY works for the host's own player right now: a remote player's inventory isn't tracked host-side (nothing reports it up), so this is a no-op for any other player_id. Prefer give_item for a remote player (granting doesn't need to know what they already have).
---@param player_id integer Must be the host's own id (see summary) or this always fails.
---@param kind string A block id from block_kinds; only a gatherable resource can be held at all.
---@param amount integer How many to remove.
---@return boolean
function api.take_item(player_id, kind, amount) end

--- How much of one resource a player's inventory currently holds, including staged give/take operations and earlier committed callbacks in this dispatch. Same host-only limitation as take_item -- a remote player's inventory isn't tracked host-side yet.
---@param player_id integer Must be the host's own id or this returns nil.
---@param kind string A block id from block_kinds.
---@return integer|nil
function api.get_resource_count(player_id, kind) end

--- Reduces a player's health, clamped at 0 -- there is no death/respawn system yet, so health just stops there.
---@param player_id integer
---@param amount number
---@return boolean
function api.damage_player(player_id, amount) end

--- Restores a player's health, clamped at 100 (max_health).
---@param player_id integer
---@param amount number
---@return boolean
function api.heal_player(player_id, amount) end

--- Sets a player's poisoned flag directly -- true starts the 1-health-per-poison_tick_secs drain (see PlayerSnapshot.poisoned), false stops it (the hook a future medication item/effect would call; nothing in the engine calls this with false on its own yet).
---@param player_id integer
---@param poisoned boolean
---@return boolean
function api.set_poisoned(player_id, poisoned) end

--- Sets a player's speed_multiplier (applied to their base walk/sprint speed).
---@param player_id integer
---@param multiplier number Clamped into [attribute_multiplier_min, attribute_multiplier_max].
---@return boolean
function api.set_player_speed(player_id, multiplier) end

--- Sets a player's jump_multiplier (applied to their base jump speed).
---@param player_id integer
---@param multiplier number Clamped into [attribute_multiplier_min, attribute_multiplier_max].
---@return boolean
function api.set_player_jump(player_id, multiplier) end

--- Moves a player straight to a position, bypassing normal movement and collision entirely (the same way replace_block bypasses mining). Resets that player's velocity to zero, so they don't keep carrying whatever momentum they had right before the jump.
---@param player_id integer
---@param x number
---@param y number
---@param z number
---@return boolean
function api.teleport_player(player_id, x, y, z) end

--- Called ~10/sec while the module is enabled. Defines a RULE module.
--- Required unless the module defines on_cast instead (exactly one of the two).
---@param api WorldApi
function on_tick(api) end

--- Runs once, immediately, when the host clicks Run. Defines an INSTANT SPELL
--- module instead of a RULE -- mutually exclusive with on_tick.
---@param api WorldApi
---@param event CastEvent
function on_cast(api, event) end

--- Fires once per creature death. Optional.
---@param api WorldApi
---@param event DeathEvent
function on_death(api, event) end

--- Fires once per real player-caused block break. Optional.
---@param api WorldApi
---@param event BlockBreakEvent
function on_block_break(api, event) end

--- Fires once per real player-caused interact-key press (E), never changing
--- the block. Optional.
---@param api WorldApi
---@param event InteractEvent
function on_interact(api, event) end

