---@meta world_api
-- World API v1.37.0 type stubs, generated by tools/gen_world_api.py.
-- Do not edit by hand. For editor autocomplete (e.g. the VS Code/sumneko Lua extension):
-- point its workspace library path at this file's directory.

---@class BlockInfo
---@field kind string
---@field name string
---@field resource_type string
---@field solid boolean
---@field opaque boolean
---@field collectible boolean
---@field hardness integer
---@field emission number
---@field ore boolean

---@class PlayerJournal
---@field stage integer
---@field title string
---@field explored_depths boolean
---@field crafted_tool boolean
---@field recipe_books integer
---@field recoveries integer
---@field complete boolean
---@field home table | nil
---@field quests_completed integer
---@field quests table

---@class QuestProgress
---@field id integer
---@field npc string
---@field title string
---@field objective string
---@field progress integer
---@field target integer
---@field completed boolean

---@class PlayerSnapshot
---@field id integer
---@field mana integer
---@field x number
---@field y number
---@field z number
---@field carrying_crystal boolean
---@field speed number
---@field vertical_speed number
---@field on_ground boolean
---@field running boolean
---@field in_water boolean
---@field health number
---@field poisoned boolean
---@field speed_multiplier number
---@field jump_multiplier number
---@field oxygen number

---@class PlayerSnapshotWithDistance : PlayerSnapshot
---@field distance number

---@class CreatureSnapshot
---@field id integer
---@field kind string
---@field x number
---@field y number
---@field z number
---@field health number
---@field max_health number
---@field can_swim boolean
---@field can_fly boolean
---@field in_water boolean

---@class CampfireSnapshot
---@field x integer
---@field y integer
---@field z integer
---@field burning boolean
---@field light_radius number
---@field light_active boolean
---@field requires_fuel boolean

---@class WaterSnapshot
---@field x integer
---@field y integer
---@field z integer
---@field surface_y integer
---@field depth integer
---@field flowing boolean
---@field flow_x number
---@field flow_z number
---@field flow_speed number
---@field visual_only boolean

---@class WaterfallSnapshot
---@field x integer
---@field y integer
---@field z integer
---@field bottom_y number
---@field height number
---@field flow_x number
---@field flow_z number
---@field sound_radius number
---@field visual_only boolean

---@class CreatureSnapshotWithDistance : CreatureSnapshot
---@field distance number

---@class BlockPos
---@field x integer
---@field y integer
---@field z integer

---@class CastEvent
---@field player_id integer
---@field target CastTarget|nil
---@field cast_id integer|nil
---@field origin CastVector|nil
---@field facing CastVector|nil
---@field hit_position CastVector|nil
---@field hit_normal CastVector|nil

---@class CastVector
---@field x number
---@field y number
---@field z number

---@class CastTarget
---@field kind string
---@field id integer|nil
---@field x integer|nil
---@field y integer|nil
---@field z integer|nil
---@field material string|nil

---@class DeathEvent
---@field kind string
---@field x number
---@field y number
---@field z number

---@class BlockBreakEvent
---@field kind string
---@field x integer
---@field y integer
---@field z integer
---@field player_id integer

---@class InteractEvent
---@field kind string
---@field x integer
---@field y integer
---@field z integer
---@field player_id integer

---@class WorldApi
---@field instant_mana_cost integer
---@field rule_mana_cost integer
---@field mana_regen_cap integer
---@field is_raining boolean
---@field campfire_light_radius number
---@field fish_spawn_clearance integer
---@field time_of_day number
---@field is_night boolean
---@field weather string
local api = {}

--- Direct lookup by connected player ID, including staged effects. Use get_player(event.player_id) for the caster; event has no coordinates.
---@param player_id integer
---@return PlayerSnapshot|nil
function api.get_player(player_id) end

--- Read this continuous rule's persistent single-object attachment, or nil for an unattached rule or a target removed earlier in this callback. Includes kind (creature/block/device), creation_id, creator_id, world_id and creation-time world_revision. Creature targets provide id, species and current x/y/z; block targets provide x/y/z and material; devices provide durable placement id, device_type and base x/y/z. Call this in on_tick instead of hard-coding a target ID. The host validates the binding before each callback. Lost/replaced targets disable the rule; unloaded block/device targets pause it. Prior world changes are not undone by detach.
---@return table|nil
function api.get_rule_target() end

--- Direct lookup by creature ID, including creatures spawned, healed, damaged or pushed in this callback. Includes slow_seconds and stun_seconds (remaining durations, zero when inactive).
---@param creature_id integer
---@return CreatureSnapshot|nil
function api.get_creature(creature_id) end

--- Heal a living creature, capped at its species maximum health. Cannot resurrect or increase maximum health. Uses the same transaction, save and replication path as creature damage.
---@param creature_id integer
---@param amount number
---@return boolean
function api.heal_creature(creature_id, amount) end

--- Apply a temporary creature status: slow halves movement and action speed; stun pauses movement and actions. Duration is 0–30 seconds of host simulation time; 0 clears that status. Reapplication replaces the remaining duration, statuses do not multiply, and stun takes precedence over slow. Remaining durations save with creatures; effects expire automatically. Changes are transactional.
---@param creature_id integer
---@param status string
---@param seconds number
---@return boolean
function api.apply_creature_status(creature_id, status, seconds) end

--- Displace a creature by dx/dy/dz, at most 8 blocks per call. Checks its body along the whole segment against loaded terrain and staged block edits; stops before obstacles. Returns false if no movement is possible, the ID is missing or displacement is invalid. Dragons are unsupported; fish remain in water. Normal host movement and body separation resume afterward. Transactional; get_creature sees the staged position. For pushing away, normalize target minus caster and multiply by the desired distance.
---@param creature_id integer
---@param dx number
---@param dy number
---@param dz number
---@return boolean
function api.push_creature(creature_id, dx, dy, dz) end

--- List canonical block IDs in stable catalog order. Use get_block_info to inspect a material; returned tables never change engine definitions.
---@return string[]
function api.get_block_kinds() end

--- Inspect a block material by ID, not coordinates. To inspect a cell use get_block_info(get_block(x,y,z)).
---@param kind string
---@return BlockInfo|nil
function api.get_block_info(kind) end

--- Check a block ID against an exact ID or a category: any, wood, ore (including coal), leaves, plant (crossed or surface-only decorations except campfire), solid, liquid (water). These same case-insensitive filters work in find_blocks and shape edits. Unknown IDs/filters never match.
---@param kind string
---@param filter string
---@return boolean
function api.block_matches(kind, filter) end

--- Distinguish loaded terrain from get_block's air fallback. Checks chunk presence and Y=0..127; does not generate chunks.
---@param x integer
---@param y integer
---@param z integer
---@return boolean
function api.is_block_loaded(x, y, z) end

--- Topmost solid block in a loaded column, including trees, construction, devices and staged edits. Unlike terrain_height this reads the actual edited world. It is not the cave floor below a player. Scans at most 128 cells.
---@param x integer
---@param z integer
---@return integer|nil
function api.surface_height(x, z) end

--- True if no solid rain-blocking block exists at or above this loaded cell. Includes staged roofs; query above a surface block to check rain exposure. Leaves block rain, water does not. Not a numeric light-level query. Scans at most 128 cells.
---@param x integer
---@param y integer
---@param z integer
---@return boolean|nil
function api.is_exposed_to_sky(x, y, z) end

--- Fill an inclusive integer box with one block kind; corner order is normalized. Optional filter selects existing materials (same categories as block_matches; omitted means any). Use kind air to excavate, filter air to build only in empty cells, or filter stone to transmute rock. At most 4096 candidate cells; every cell must be loaded and within Y=0..127. Shares replace_block's remaining 32 edits per rule callback / 300 per cast; unchanged cells cost no edits. Rejects the whole call if it would exceed that remaining budget or modify bedrock or any occupied device cell. Cannot place bedrock. No partial fills. A nil result stages nothing and consumes no edit allowance. No inventory costs or drops; these are explicit world-edit powers, not player crafting. Larger builds must use small batches across on_tick calls. Shape scans charge candidate volume times (1 + earlier staged edits) native work.

---@param x1 integer
---@param y1 integer
---@param z1 integer
---@param x2 integer
---@param y2 integer
---@param z2 integer
---@param kind string
---@param filter string
---@return integer|nil
function api.fill_box(x1, y1, z1, x2, y2, z2, kind, filter) end

--- Fill integer cells whose coordinate distance from the integer center is <= radius (0..7). Same filters, all-or-nothing behavior, protected blocks, loaded-cell requirements and shared edit allowance as fill_box. A bounding-cube native-work charge is applied before scanning. For example radius 2 changes at most 33 cells: suitable for a cast, too large for an otherwise empty tick budget.
---@param cx integer
---@param cy integer
---@param cz integer
---@param radius number
---@param kind string
---@param filter string
---@return integer|nil
function api.fill_sphere(cx, cy, cz, radius, kind, filter) end

--- Read a connected player's saved campkeeper contracts, recovery location, and twenty traveler quests (quests and quests_completed added in 1.28.0). Detached table; scripts cannot directly claim rewards or change built-in progress. Quest givers are peaceful patrol NPCs, separate from combat creatures. One random traveler starts near camp; more are discovered roughly every 100 blocks on dry land. Repeated roles share the same per-player quest completion.
---@param player_id integer
---@return PlayerJournal|nil
function api.get_player_journal(player_id) end

--- Read the selected resource/equipment ID, e.g. crystal or pickaxe, or spell:<id> for an available remembered spell. Returns nil for missing players, empty slots, unavailable spells or depleted stacks; respects staged inventory changes. Crystals are ordinary held resources and emit no portable light. Torches occupy a separate left-hand slot, so this query continues to report the right-hand tool. Unlike carrying_crystal, this reflects the current selection and inventory.
---@param player_id integer
---@return string|nil
function api.get_equipped_item(player_id) end

--- Complete detached inventory: resources maps resource IDs to counts, items maps all 19 available equipment IDs to counts (see get_item_recipe), elements maps earth/fire/water/life/death to counts, and mana is an integer. Includes zeros, staged changes and earlier committed callbacks; nil for missing player.
---@param player_id integer
---@return table|nil
function api.get_player_inventory(player_id) end

--- Available mana, including staged changes. During an instant, the engine has already reserved its 5 mana cast fee; do not subtract that fee again.
---@param player_id integer
---@return integer|nil
function api.get_mana(player_id) end

--- Element count; names earth, fire, water, life, death are case insensitive. nil for missing player/unknown element.
---@param player_id integer
---@param element string
---@return integer|nil
function api.get_element_count(player_id, element) end

--- Count any equipment ID listed by get_player_inventory or collectible resource ID. nil for unknown player/ID.
---@param player_id integer
---@param kind string
---@return integer|nil
function api.get_item_count(player_id, kind) end

--- Grant mana as an explicit rule reward. Not automatic recovery. Amount must be 1..item_grant_max; false on invalid player, amount or overflow.
---@param player_id integer
---@param amount integer
---@return boolean
function api.give_mana(player_id, amount) end

--- Reserve an additional custom mana cost; false leaves balances unchanged if insufficient. With host mana-free testing enabled, valid requests succeed without reducing mana. Do not charge the engine instant/rule fee again. Amount 1..item_grant_max.
---@param player_id integer
---@param amount integer
---@return boolean
function api.take_mana(player_id, amount) end

--- Grant an explicit elemental reward. Names earth/fire/water/life/death are case insensitive. Amount 1..item_grant_max; invalid input/overflow returns false.
---@param player_id integer
---@param element string
---@param amount integer
---@return boolean
function api.give_element(player_id, element, amount) end

--- Consume elements atomically; false if invalid input or insufficient balance. Amount 1..item_grant_max.
---@param player_id integer
---@param element string
---@param amount integer
---@return boolean
function api.take_element(player_id, element, amount) end

--- Create one equipment item using the same materials, mana and discovered-recipe requirements as inventory. Optional amount defaults to 1 and must equal 1. Specialist recipes require the player to read the corresponding world recipe book. No free gear grant. Read get_item_recipe first.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean
function api.craft_item(player_id, kind, amount) end

--- Consume one owned equipment item and its mana cost; return salvaged materials per get_item_recipe. Optional amount must equal 1. Recipe knowledge is not required for salvage.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean
function api.decompose_item(player_id, kind, amount) end

--- Consume 1..item_grant_max resource units and the same amount of mana, granting their catalog elements. Optional amount defaults to 1. False on invalid inputs, missing resources/mana or overflow; no partial changes.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean
function api.decompose_resource(player_id, kind, amount) end

--- Convert elements into mana at the host crafting registry conversion rate. Amount 1..item_grant_max, default 1. No additional mana fee. False if invalid/insufficient/overflow.
---@param player_id integer
---@param element string
---@param amount integer
---@return boolean
function api.convert_elements_to_mana(player_id, element, amount) end

--- Per-unit composition from the host crafting catalog, keyed by earth/fire/water/life/death including zeros. nil for non-resource ID; a zero composition cannot be decomposed.
---@param kind string
---@return table|nil
function api.get_resource_elements(kind) end

--- Equipment IDs: axe, pickaxe, sword, forester_axe, prospector_pick, spade, sickle, spear, dagger, warhammer, ember_wand, tide_wand, life_staff, survey_lantern, trail_charm, leaping_charm, diving_charm, feather_charm, torch. Returns create/decompose tables with resources={resource_id=count} and mana=cost. Specialist items also return recipe_book and recipe_book_bit; require that bit in get_player_journal(player_id).recipe_books to craft. Create consumes materials; decompose returns them. nil for unknown equipment.
---@param kind string
---@return table|nil
function api.get_item_recipe(kind) end

--- Preferred for create campfire nearby / near me (including obvious typos such as camfpire). Call once in on_cast with event.player_id and radius 6. Searches real loaded edited ground within radius and +/-4 vertical blocks; avoids players by 2 horizontal blocks, requires support and fire/smoke clearance, may replace a small ground plant. No guessed terrain_height or spawn_creature calls.
---@param player_id integer
---@param radius number Clamped to 2..8 blocks; 6 recommended.
---@return CampfireSnapshot|nil
function api.place_campfire_near_player(player_id, radius) end

--- List automation devices in deterministic cell order (at most 64 by default). Each snapshot has x/y/z, kind, enabled, mana, signal, activity, recipe, element, rotation, reserve, progress (0..1), items and output maps. Matter map keys are element:earth/fire/water/life/death, resource:<block_id>, item:<equipment_id> or creature:<kind>. Returned tables are copies. Production runs separately on fixed host ticks; never call an LLM for production.
---@return table[]
function api.get_devices() end

--- Inspect one automation device at any of its occupied cells; coordinates in the snapshot identify its base. Same fields as get_devices, plus eject_contents for chest/smelter mode, fuel_heat for smelter fuel uses, height in blocks, and powered_ticks for remaining paid lantern/altar/shrine runtime in 100ms ticks. All occupied cells report automation_device through get_block and cannot be overwritten with replace_block; use player packing controls to preserve contents.
---@param x integer
---@param y integer
---@param z integer
---@return table|nil
function api.get_device(x, y, z) end

--- Enable or pause an automation device without losing its paid cycle, stored mana or items. For example, disable condensers at night. Transactional: errors roll back changes. Costs one shared block-edit budget unit.
---@param x integer
---@param y integer
---@param z integer
---@param enabled boolean
---@return boolean
function api.set_device_enabled(x, y, z, enabled) end

--- Update supplied settings only: enabled, recipe (existing crafting recipe ID), element (earth/fire/water/life/death), reserve, input (west/east/north/south/up/down), outputs (ordered face array), routing (round_robin/priority/filter), filter (matter ID), sensor_x/sensor_y/sensor_z, sensor_item (empty for total), lower, upper, signal_mode (state/pulse/numeric), invert, valve_matter, eject_contents (chest/smelter: true ejects bags/living creatures nearby, false stores or feeds through its output port; defaults true). Lower must be below upper. Sensor targets a chest or vessel within 16 blocks. An inverted valve opens while signal is off for upper/lower stock control. Ports rotate with the device; inputs and outputs must differ. Current paid cycles retain their recipe. One shared block-edit budget unit; rollback on callback error.
---@param x integer
---@param y integer
---@param z integer
---@param settings table
---@return boolean
function api.configure_device(x, y, z, settings) end

--- Build an automation device within 7 blocks of a connected player, paying resource costs from their inventory. Kinds: collector, vessel, condenser, dissipator, conduit, channel, splitter, chest, workshop, sensor, valve, signal, smelter, lantern, dark_altar, shrine. Rotation is 0..3 clockwise quarter-turns. Footprints are one block; lantern is 3 blocks high, dark_altar and shrine 2, others 1. Checks clearance over full height, player collision, limits and funds. Opposing same-type ports connect automatically at the base. Lantern uses 1 mana per 10 seconds for white-blue light. Dark altar damages and shrine heals all creatures within radius 6 by 3 health each second, costing 1 mana per second. They accept personal refills through F and mana input on horizontal/bottom base faces. Uses one shared block-edit budget; inventory and placement roll back on callback failure.
---@param player_id integer
---@param kind string
---@param x integer
---@param y integer
---@param z integer
---@param rotation integer
---@return boolean
function api.place_device(player_id, kind, x, y, z, rotation) end

--- Inspect a campfire block, including burning and night-light state.
---@param x integer
---@param y integer
---@param z integer
---@return CampfireSnapshot|nil
function api.get_campfire(x, y, z) end

--- Find nearby campfire snapshots; respects callback scan budgets. Prefer small radii and avoid nested scans.
---@param x integer
---@param y integer
---@param z integer
---@param radius number Clamped to 0..12.
---@return CampfireSnapshot[]
function api.find_campfires(x, y, z, radius) end

--- Place an indefinitely burning campfire on loaded grass, soil, sand, or stone with four air blocks above the support. Uses one shared block edit; no recipe or inventory cost.
---@param x integer
---@param y integer
---@param z integer
---@return boolean
function api.place_campfire(x, y, z) end

--- Inspect water depth, surface elevation, and the visual river/stream current. No fluid simulation or writable flow override.
---@param x integer
---@param y integer
---@param z integer
---@return WaterSnapshot|nil
function api.get_water(x, y, z) end

--- Inspect spills at a source water block. Requires open sky, an adjacent open drop, loaded neighbors, and lower receiving water. Use get_water().surface_y-1 to query its top block.
---@param x integer
---@param y integer
---@param z integer
---@return WaterfallSnapshot[]
function api.get_waterfalls(x, y, z) end

--- Check a submerged fish body and full 7x7 water layer centered at floor(x,y,z). Reads staged edits.
---@param x number
---@param y number
---@param z number
---@return boolean
function api.can_spawn_fish(x, y, z) end

--- Spawn a swimming fish only where can_spawn_fish succeeds. Reads staged water edits and shares the normal creature spawn budget, including failed attempts. Use chase(id,x,y,z) each tick to guide it within connected water.
---@param x number
---@param y number
---@param z number
---@return integer|nil
function api.spawn_fish(x, y, z) end

--- Every connected player.
---@return PlayerSnapshot[]
function api.players() end

--- The single closest connected player to THREE numeric coordinates (x, y, z), not a player ID or position table. To find the caster, match event.player_id in api.players(); for a nearby campfire use place_campfire_near_player(event.player_id, 6).
---@param x number
---@param y number
---@param z number
---@return PlayerSnapshotWithDistance|nil
function api.nearest_player(x, y, z) end

--- Every creature in the world.
---@return CreatureSnapshot[]
function api.creatures() end

--- Creatures of one kind within a radius of a point.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch", "zombie", "skeleton", "dragon_green", "dragon_red", "fish", or "any". An unrecognized string is treated the same as "any" -- it is NOT an error, so a typo silently matches every creature instead of failing loudly.
---@param cx number
---@param cy number
---@param cz number
---@param radius number Clamped into [0, find_radius_max].
---@return CreatureSnapshot[]
function api.find_creatures(kind, cx, cy, cz, radius) end

--- The single closest creature of one kind to a point. No radius argument -- it searches every creature in the world unconditionally.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch", "zombie", "skeleton", "dragon_green", "dragon_red", "fish", or "any" -- same unrecognized-string-means-any behavior as find_creatures.
---@param x number
---@param y number
---@param z number
---@return CreatureSnapshotWithDistance|nil
function api.nearest_creature(kind, x, y, z) end

--- The block at an integer position.
---@param x integer
---@param y integer
---@param z integer
---@return string
function api.get_block(x, y, z) end

--- Positions of every block of one kind within a radius of a point.
---@param kind string Exact block ID or category any, wood, ore, leaves, plant, solid, liquid; see block_matches. Unknown filters return an empty result. Legacy find_creatures instead treats unknown kinds as any; do not rely on that behavior.
---@param cx integer
---@param cy integer
---@param cz integer
---@param radius number Clamped into [0, find_radius_max].
---@return BlockPos[]
function api.find_blocks(kind, cx, cy, cz, radius) end

--- Procedural terrain elevation, ignoring construction and block edits. Use surface_height for the top solid block in actual loaded terrain. Neither method locates an underground cave floor.
---@param x integer
---@param z integer
---@return integer
function api.terrain_height(x, z) end

--- Straight-line distance between two points. Prefer this over writing your own sqrt(dx*dx+dy*dy+dz*dz).
---@param x1 number
---@param y1 number
---@param z1 number
---@param x2 number
---@param y2 number
---@param z2 number
---@return number
function api.distance(x1, y1, z1, x2, y2, z2) end

--- Makes a creature move toward a point at increased speed, overriding explicit targeting and suppressing automatic attacks while the chase lease is active. Call it again every tick to keep it chasing -- stop calling it and the creature reverts to normal wandering within about a third of a second (use ignore to stop chasing).
---@param creature_id integer
---@param x number
---@param y number
---@param z number
---@return nil
function api.chase(creature_id, x, y, z) end

--- On_tick only: prevent melee damage/attack animation from creature kind against this player without changing creature aggression or creature-to-creature combat. Rule-owned temporary policy: refresh every tick while condition holds; an empty next tick removes it. Disable/delete/error releases it; other rules' protections remain. Saved rules recompute policies after reload.
---@param player_id integer
---@param kind string
---@return boolean
function api.protect_player(player_id, kind) end

--- On_tick only: temporarily prevent this creature's melee attacks against all targets. Same rule-owned cleanup as protect_player. Does not change underlying aggression, target or movement. Refresh only while the condition holds.
---@param creature_id integer
---@return boolean
function api.suppress_creature_attacks(creature_id) end

--- Overrides persist until changed and survive save/reload; disabling a rule does not undo them. Read current behavior settings: aggressive boolean, mode (auto/chase/attack/ignore), optional target_type (player/creature) and target_id. Nil for missing creature. Target fields describe explicit selection, not automatic aggro. Attack mode is intent, not proof an attack landed.
---@param creature_id integer
---@return table|nil
function api.get_behavior(creature_id) end

--- Set automatic player aggression, cancel explicit targeting and restore normal wandering/automatic AI. False makes even hostile species peaceful. True lets passive species attack too (2 damage, 1.5 reach, 2 second cooldown, 16 block detection).
---@param creature_id integer
---@param aggressive boolean
---@return boolean
function api.set_aggressive(creature_id, aggressive) end

--- Select a specific live target without starting an action. target_type must be player or creature. Self-targets are rejected. Follow with attack or chase_target.
---@param creature_id integer
---@param target_type string
---@param target_id integer
---@return boolean
function api.set_target(creature_id, target_type, target_id) end

--- Select nearest live target of kind player, sheep, chicken, cow, wolf, stone_golem, stinger, goblin, sunscorch, zombie, skeleton, dragon_green, dragon_red, or fish within radius (clamped to query limit). Excludes self. Returns target ID or nil; no match clears selection. Does not start an action; follow with attack or chase_target.
---@param creature_id integer
---@param kind string
---@param radius number
---@return integer|nil
function api.select_target(creature_id, kind, radius) end

--- Follow selected live target as it moves, without attacking; overrides built-in hostility. Returns false without a target.
---@param creature_id integer
---@return boolean
function api.chase_target(creature_id) end

--- Pursue selected live target and deal damage in melee range on species cooldown, including creature versus creature. Passive species can attack. Does not deal instant damage; use damage for that. Returns false without target.
---@param creature_id integer
---@return boolean
function api.attack(creature_id) end

--- Cancel target, chase and aggression; resume peaceful wandering. Overrides built-in hostile AI. Use set_aggressive to restore automatic behavior.
---@param creature_id integer
---@return boolean
function api.ignore(creature_id) end

--- Kill creature immediately with normal death sound, despawn and on_death event, like destroy. Returns false if already dead or missing.
---@param creature_id integer
---@return boolean
function api.die(creature_id) end

--- Reduces a creature's health. Fires on_death (to every module, not just the caller) if this brings health to zero or below, and despawns it.
---@param creature_id integer
---@param amount number
---@return nil
function api.damage(creature_id, amount) end

--- Removes a creature immediately regardless of remaining health, and fires on_death.
---@param creature_id integer
---@return nil
function api.destroy(creature_id) end

--- Spawns a new creature at a position. sheep/chicken/cow are passive by default; set_aggressive or attack can enable combat. stone_golem, wolf, stinger, goblin, sunscorch, zombie, skeleton, dragon_green, and dragon_red are different: all nine hostile entirely on their own, with no Lua involved -- each closes on and periodically damages the nearest player within its own aggro radius. stone_golem is large, slow, and hits hardest on the longest cooldown; sunscorch is a rare, tanky ghost that never gives up a chase and (like stone_golem) never speeds up while chasing -- no run animation, mechanically identical pace whether wandering or aggroed; goblin is a mid-weight melee bruiser (moderate speed/damage/cooldown, tankier than wolf); wolf is faster and lighter; stinger is fastest to attack (shortest cooldown) but hits lightest and is the most fragile. Zombies and skeletons only walk, including while chasing, and use melee attacks. Dragons are giant solitary predators: they walk, take off, fly and attack in either mode, and land again. Dragon homes must be at least 320 blocks apart across both colors; spawn returns nil inside another dragon territory, including earlier spawns in the same callback. Dragons stay within 64 blocks of home even during scripted chases. Fish are passive swimmers: they require a full 7x7 horizontal water area centered on the spawn position (three water blocks in each horizontal direction), including water around their whole body. Fish spawns in smaller pools or on land return nil. Fish only swim through connected water and occasionally jump straight up and return to the same water column. Fish never attack, even if aggression is enabled. Only spawn a hostile one when a hostile/dangerous creature is actually what the request wants.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", or "sunscorch", "zombie", "skeleton", "dragon_green", "dragon_red", "fish"; anything else (including a typo) silently becomes "sheep" -- not an error.
---@param x number
---@param y number
---@param z number
---@return integer|nil
function api.spawn_creature(kind, x, y, z) end

--- Spawns a new creature at a random point within radius blocks of a player (horizontally; height snaps to terrain). For fish, searches nearby loaded water instead, requiring the same pool-size check as spawn_creature; returns nil if no suitable pool is found. Prefer this over spawn_creature plus your own random offset when the rule is about spawning near a specific player.
---@param player_id integer
---@param kind string Same kinds as spawn_creature, including zombie, skeleton, dragon_green and dragon_red. Use these exact singular identifiers, not model variant filenames, plurals or dragon. Unknown strings silently spawn sheep.
---@param radius number Clamped into [1, find_radius_max] -- note the floor is 1, not 0, unlike the find_* methods.
---@return integer|nil
function api.spawn_creature_near_player(player_id, kind, radius) end

--- Changes one block.
---@param x integer
---@param y integer
---@param z integer
---@param kind string A block id from block_kinds (e.g. "air" to clear a block).
---@return boolean
function api.replace_block(x, y, z, kind) end

--- Sets the weather directly, and resets the engine's own random weather timer (so it won't immediately pick something else out from under you).
---@param name string "clear" is also accepted, as an alias for "sunny" (its name before the 5-weather system existed).
---@return nil
function api.set_weather(name) end

--- Shorthand for set_weather("rain").
---@return nil
function api.start_rain() end

--- Shorthand for set_weather("sunny").
---@return nil
function api.stop_rain() end

--- Sets the time of day directly.
---@param t number Wrapped into [0,1) (e.g. -0.25 and 1.25 both become 0.75), same scale as api.time_of_day.
---@return nil
function api.set_time_of_day(t) end

--- Shorthand for set_time_of_day(0.0).
---@return nil
function api.set_time_dawn() end

--- Shorthand for set_time_of_day(0.5) -- sunset, night begins.
---@return nil
function api.set_time_night() end

--- Queues a notification and server log message, emitted only if the callback commits. At most 8 messages per callback, each at most 512 UTF-8 bytes; exceeding either limit aborts execution with an uncatchable budget failure.
---@param message string
---@return nil
function api.broadcast(message) end

--- Grants collectible resources or equipment IDs listed by get_player_inventory into a connected player inventory, bypassing crafting costs. Equipment amounts must be 1..item_grant_max and overflow is rejected; legacy resource grants clamp the amount and saturate balances. Only use this when the request explicitly asks to add to a player's inventory/resources -- for everything else ("add 100 stone", "fill this area with water"), prefer replace_block to place blocks in the world instead.
---@param player_id integer Target player (matches PlayerSnapshot.id).
---@param kind string A collectible resource ID or equipment ID listed by get_player_inventory. Air, water and campfire are not inventory stacks.
---@param amount integer Resource grants clamp into [0, item_grant_max]; equipment requires 1..item_grant_max.
---@return boolean
function api.give_item(player_id, kind, amount) end

--- Atomically remove collectible resources or equipment IDs listed by get_player_inventory from any connected player. Includes staged changes; failure rolls back. Equipment amounts must be 1..item_grant_max. This consumes items without decomposition returns.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean
function api.take_item(player_id, kind, amount) end

--- Read a resource count for any connected player, including guests. Includes staged inventory changes and earlier accepted callbacks.
---@param player_id integer
---@param kind string
---@return integer|nil
function api.get_resource_count(player_id, kind) end

--- Legacy resource-only inventory map, including zeros and staged changes. Use get_player_inventory for resources, equipment, elements and mana together. Editing returned tables changes nothing.
---@param player_id integer
---@return table|nil
function api.get_inventory(player_id) end

--- Whether a connected player holds at least amount of a collectible resource. Amount defaults to 1 when omitted. To check absence use api.has_resource(id, kind) == false; nil means invalid input, not absence.
---@param player_id integer
---@param kind string
---@param amount integer Positive minimum count; default 1.
---@return boolean|nil
function api.has_resource(player_id, kind, amount) end

--- Checks equipment IDs listed by get_player_inventory or collectible resource IDs. Omitted amount defaults to 1; false means insufficient count, nil means missing player or invalid ID/amount. Includes staged changes.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean|nil
function api.has_item(player_id, kind, amount) end

--- Reduces a player's health, clamped at 0 -- there is no death/respawn system yet, so health just stops there.
---@param player_id integer
---@param amount number
---@return boolean
function api.damage_player(player_id, amount) end

--- Restores a player's health, clamped at 100 (max_health).
---@param player_id integer
---@param amount number
---@return boolean
function api.heal_player(player_id, amount) end

--- Sets a player's poisoned flag directly -- true starts the 1-health-per-poison_tick_secs drain (see PlayerSnapshot.poisoned), false stops it (the hook a future medication item/effect would call; nothing in the engine calls this with false on its own yet).
---@param player_id integer
---@param poisoned boolean
---@return boolean
function api.set_poisoned(player_id, poisoned) end

--- Sets a player's speed_multiplier (applied to their base walk/sprint speed).
---@param player_id integer
---@param multiplier number Clamped into [attribute_multiplier_min, attribute_multiplier_max].
---@return boolean
function api.set_player_speed(player_id, multiplier) end

--- Sets a player's jump_multiplier (applied to their base jump speed).
---@param player_id integer
---@param multiplier number Clamped into [attribute_multiplier_min, attribute_multiplier_max].
---@return boolean
function api.set_player_jump(player_id, multiplier) end

--- Moves a player straight to a position, bypassing normal movement and collision entirely (the same way replace_block bypasses mining). Resets that player's velocity to zero, so they don't keep carrying whatever momentum they had right before the jump.
---@param player_id integer
---@param x number
---@param y number
---@param z number
---@return boolean
function api.teleport_player(player_id, x, y, z) end

--- Called ~10/sec while the module is enabled. Defines a RULE module.
--- Required unless the module defines on_cast instead (exactly one of the two).
---@param api WorldApi
function on_tick(api) end

--- Runs once, immediately, when the host clicks Run. Defines an INSTANT SPELL
--- module instead of a RULE -- mutually exclusive with on_tick.
---@param api WorldApi
---@param event CastEvent
function on_cast(api, event) end

--- Fires once per creature death. Optional.
---@param api WorldApi
---@param event DeathEvent
function on_death(api, event) end

--- Fires once per real player-caused block break. Optional.
---@param api WorldApi
---@param event BlockBreakEvent
function on_block_break(api, event) end

--- Fires once per real player-caused interact-key press (E), never changing
--- the block. Optional.
---@param api WorldApi
---@param event InteractEvent
function on_interact(api, event) end

