---@meta world_api
-- World API v1.21.0 type stubs, generated by tools/gen_world_api.py.
-- Do not edit by hand. For editor autocomplete (e.g. the VS Code/sumneko Lua extension):
-- point its workspace library path at this file's directory.

---@class PlayerSnapshot
---@field id integer
---@field x number
---@field y number
---@field z number
---@field carrying_crystal boolean
---@field speed number
---@field vertical_speed number
---@field on_ground boolean
---@field running boolean
---@field in_water boolean
---@field health number
---@field poisoned boolean
---@field speed_multiplier number
---@field jump_multiplier number
---@field oxygen number

---@class PlayerSnapshotWithDistance : PlayerSnapshot
---@field distance number

---@class CreatureSnapshot
---@field id integer
---@field kind string
---@field x number
---@field y number
---@field z number
---@field health number
---@field max_health number
---@field can_swim boolean
---@field can_fly boolean
---@field in_water boolean

---@class CampfireSnapshot
---@field x integer
---@field y integer
---@field z integer
---@field burning boolean
---@field light_radius number
---@field light_active boolean
---@field requires_fuel boolean

---@class WaterSnapshot
---@field x integer
---@field y integer
---@field z integer
---@field surface_y integer
---@field depth integer
---@field flowing boolean
---@field flow_x number
---@field flow_z number
---@field flow_speed number
---@field visual_only boolean

---@class WaterfallSnapshot
---@field x integer
---@field y integer
---@field z integer
---@field bottom_y number
---@field height number
---@field flow_x number
---@field flow_z number
---@field sound_radius number
---@field visual_only boolean

---@class CreatureSnapshotWithDistance : CreatureSnapshot
---@field distance number

---@class BlockPos
---@field x integer
---@field y integer
---@field z integer

---@class CastEvent
---@field player_id integer

---@class DeathEvent
---@field kind string
---@field x number
---@field y number
---@field z number

---@class BlockBreakEvent
---@field kind string
---@field x integer
---@field y integer
---@field z integer
---@field player_id integer

---@class InteractEvent
---@field kind string
---@field x integer
---@field y integer
---@field z integer
---@field player_id integer

---@class WorldApi
---@field is_raining boolean
---@field campfire_light_radius number
---@field fish_spawn_clearance integer
---@field time_of_day number
---@field is_night boolean
---@field weather string
local api = {}

--- Preferred for create campfire nearby / near me (including obvious typos such as camfpire). Call once in on_cast with event.player_id and radius 6. Searches real loaded edited ground within radius and +/-4 vertical blocks; avoids players by 2 horizontal blocks, requires support and fire/smoke clearance, may replace a small ground plant. No guessed terrain_height or spawn_creature calls.
---@param player_id integer
---@param radius number Clamped to 2..8 blocks; 6 recommended.
---@return CampfireSnapshot|nil
function api.place_campfire_near_player(player_id, radius) end

--- Inspect a campfire block, including burning and night-light state.
---@param x integer
---@param y integer
---@param z integer
---@return CampfireSnapshot|nil
function api.get_campfire(x, y, z) end

--- Find nearby campfire snapshots; respects callback scan budgets. Prefer small radii and avoid nested scans.
---@param x integer
---@param y integer
---@param z integer
---@param radius number Clamped to 0..12.
---@return CampfireSnapshot[]
function api.find_campfires(x, y, z, radius) end

--- Place an indefinitely burning campfire on loaded grass, soil, sand, or stone with four air blocks above the support. Uses one shared block edit; no recipe or inventory cost.
---@param x integer
---@param y integer
---@param z integer
---@return boolean
function api.place_campfire(x, y, z) end

--- Inspect water depth, surface elevation, and the visual river/stream current. No fluid simulation or writable flow override.
---@param x integer
---@param y integer
---@param z integer
---@return WaterSnapshot|nil
function api.get_water(x, y, z) end

--- Inspect spills at a source water block. Requires open sky, an adjacent open drop, loaded neighbors, and lower receiving water. Use get_water().surface_y-1 to query its top block.
---@param x integer
---@param y integer
---@param z integer
---@return WaterfallSnapshot[]
function api.get_waterfalls(x, y, z) end

--- Check a submerged fish body and full 7x7 water layer centered at floor(x,y,z). Reads staged edits.
---@param x number
---@param y number
---@param z number
---@return boolean
function api.can_spawn_fish(x, y, z) end

--- Spawn a swimming fish only where can_spawn_fish succeeds. Reads staged water edits and shares the normal creature spawn budget, including failed attempts. Use chase(id,x,y,z) each tick to guide it within connected water.
---@param x number
---@param y number
---@param z number
---@return integer|nil
function api.spawn_fish(x, y, z) end

--- Every connected player.
---@return PlayerSnapshot[]
function api.players() end

--- The single closest connected player to THREE numeric coordinates (x, y, z), not a player ID or position table. To find the caster, match event.player_id in api.players(); for a nearby campfire use place_campfire_near_player(event.player_id, 6).
---@param x number
---@param y number
---@param z number
---@return PlayerSnapshotWithDistance|nil
function api.nearest_player(x, y, z) end

--- Every creature in the world.
---@return CreatureSnapshot[]
function api.creatures() end

--- Creatures of one kind within a radius of a point.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch", "zombie", "skeleton", "dragon_green", "dragon_red", "fish", or "any". An unrecognized string is treated the same as "any" -- it is NOT an error, so a typo silently matches every creature instead of failing loudly.
---@param cx number
---@param cy number
---@param cz number
---@param radius number Clamped into [0, find_radius_max].
---@return CreatureSnapshot[]
function api.find_creatures(kind, cx, cy, cz, radius) end

--- The single closest creature of one kind to a point. No radius argument -- it searches every creature in the world unconditionally.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", "sunscorch", "zombie", "skeleton", "dragon_green", "dragon_red", "fish", or "any" -- same unrecognized-string-means-any behavior as find_creatures.
---@param x number
---@param y number
---@param z number
---@return CreatureSnapshotWithDistance|nil
function api.nearest_creature(kind, x, y, z) end

--- The block at an integer position.
---@param x integer
---@param y integer
---@param z integer
---@return string
function api.get_block(x, y, z) end

--- Positions of every block of one kind within a radius of a point.
---@param kind string A block id from block_kinds, OR the special category alias "wood" (matches any tree species: oak_wood, spruce_wood, birch_wood, cherry_wood). Unlike find_creatures' kind, an unrecognized string here returns an EMPTY result, not "match everything" -- this asymmetry is a real gotcha, not a design you can rely on being consistent across query methods.
---@param cx integer
---@param cy integer
---@param cz integer
---@param radius number Clamped into [0, find_radius_max].
---@return BlockPos[]
function api.find_blocks(kind, cx, cy, cz, radius) end

--- The integer y of the topmost solid ground block at a column. Useful for placing/spawning things at the correct height instead of guessing.
---@param x integer
---@param z integer
---@return integer
function api.terrain_height(x, z) end

--- Straight-line distance between two points. Prefer this over writing your own sqrt(dx*dx+dy*dy+dz*dz).
---@param x1 number
---@param y1 number
---@param z1 number
---@param x2 number
---@param y2 number
---@param z2 number
---@return number
function api.distance(x1, y1, z1, x2, y2, z2) end

--- Makes a creature move toward a point at increased speed, overriding explicit targeting and suppressing automatic attacks while the chase lease is active. Call it again every tick to keep it chasing -- stop calling it and the creature reverts to normal wandering within about a third of a second (use ignore to stop chasing).
---@param creature_id integer
---@param x number
---@param y number
---@param z number
---@return nil
function api.chase(creature_id, x, y, z) end

--- On_tick only: prevent melee damage/attack animation from creature kind against this player without changing creature aggression or creature-to-creature combat. Rule-owned temporary policy: refresh every tick while condition holds; an empty next tick removes it. Disable/delete/error releases it; other rules' protections remain. Saved rules recompute policies after reload.
---@param player_id integer
---@param kind string
---@return boolean
function api.protect_player(player_id, kind) end

--- On_tick only: temporarily prevent this creature's melee attacks against all targets. Same rule-owned cleanup as protect_player. Does not change underlying aggression, target or movement. Refresh only while the condition holds.
---@param creature_id integer
---@return boolean
function api.suppress_creature_attacks(creature_id) end

--- Overrides persist until changed and survive save/reload; disabling a rule does not undo them. Read current behavior settings: aggressive boolean, mode (auto/chase/attack/ignore), optional target_type (player/creature) and target_id. Nil for missing creature. Target fields describe explicit selection, not automatic aggro. Attack mode is intent, not proof an attack landed.
---@param creature_id integer
---@return table|nil
function api.get_behavior(creature_id) end

--- Set automatic player aggression, cancel explicit targeting and restore normal wandering/automatic AI. False makes even hostile species peaceful. True lets passive species attack too (2 damage, 1.5 reach, 2 second cooldown, 16 block detection).
---@param creature_id integer
---@param aggressive boolean
---@return boolean
function api.set_aggressive(creature_id, aggressive) end

--- Select a specific live target without starting an action. target_type must be player or creature. Self-targets are rejected. Follow with attack or chase_target.
---@param creature_id integer
---@param target_type string
---@param target_id integer
---@return boolean
function api.set_target(creature_id, target_type, target_id) end

--- Select nearest live target of kind player, sheep, chicken, cow, wolf, stone_golem, stinger, goblin, sunscorch, zombie, skeleton, dragon_green, dragon_red, or fish within radius (clamped to query limit). Excludes self. Returns target ID or nil; no match clears selection. Does not start an action; follow with attack or chase_target.
---@param creature_id integer
---@param kind string
---@param radius number
---@return integer|nil
function api.select_target(creature_id, kind, radius) end

--- Follow selected live target as it moves, without attacking; overrides built-in hostility. Returns false without a target.
---@param creature_id integer
---@return boolean
function api.chase_target(creature_id) end

--- Pursue selected live target and deal damage in melee range on species cooldown, including creature versus creature. Passive species can attack. Does not deal instant damage; use damage for that. Returns false without target.
---@param creature_id integer
---@return boolean
function api.attack(creature_id) end

--- Cancel target, chase and aggression; resume peaceful wandering. Overrides built-in hostile AI. Use set_aggressive to restore automatic behavior.
---@param creature_id integer
---@return boolean
function api.ignore(creature_id) end

--- Kill creature immediately with normal death sound, despawn and on_death event, like destroy. Returns false if already dead or missing.
---@param creature_id integer
---@return boolean
function api.die(creature_id) end

--- Reduces a creature's health. Fires on_death (to every module, not just the caller) if this brings health to zero or below, and despawns it.
---@param creature_id integer
---@param amount number
---@return nil
function api.damage(creature_id, amount) end

--- Removes a creature immediately regardless of remaining health, and fires on_death.
---@param creature_id integer
---@return nil
function api.destroy(creature_id) end

--- Spawns a new creature at a position. sheep/chicken/cow are passive by default; set_aggressive or attack can enable combat. stone_golem, wolf, stinger, goblin, sunscorch, zombie, skeleton, dragon_green, and dragon_red are different: all nine hostile entirely on their own, with no Lua involved -- each closes on and periodically damages the nearest player within its own aggro radius. stone_golem is large, slow, and hits hardest on the longest cooldown; sunscorch is a rare, tanky ghost that never gives up a chase and (like stone_golem) never speeds up while chasing -- no run animation, mechanically identical pace whether wandering or aggroed; goblin is a mid-weight melee bruiser (moderate speed/damage/cooldown, tankier than wolf); wolf is faster and lighter; stinger is fastest to attack (shortest cooldown) but hits lightest and is the most fragile. Zombies and skeletons only walk, including while chasing, and use melee attacks. Dragons are giant solitary predators: they walk, take off, fly and attack in either mode, and land again. Dragon homes must be at least 320 blocks apart across both colors; spawn returns nil inside another dragon territory, including earlier spawns in the same callback. Dragons stay within 64 blocks of home even during scripted chases. Fish are passive swimmers: they require a full 7x7 horizontal water area centered on the spawn position (three water blocks in each horizontal direction), including water around their whole body. Fish spawns in smaller pools or on land return nil. Fish only swim through connected water and occasionally jump straight up and return to the same water column. Fish never attack, even if aggression is enabled. Only spawn a hostile one when a hostile/dangerous creature is actually what the request wants.
---@param kind string "sheep", "chicken", "stone_golem", "wolf", "stinger", "cow", "goblin", or "sunscorch", "zombie", "skeleton", "dragon_green", "dragon_red", "fish"; anything else (including a typo) silently becomes "sheep" -- not an error.
---@param x number
---@param y number
---@param z number
---@return integer|nil
function api.spawn_creature(kind, x, y, z) end

--- Spawns a new creature at a random point within radius blocks of a player (horizontally; height snaps to terrain). For fish, searches nearby loaded water instead, requiring the same pool-size check as spawn_creature; returns nil if no suitable pool is found. Prefer this over spawn_creature plus your own random offset when the rule is about spawning near a specific player.
---@param player_id integer
---@param kind string Same silent-default-to-sheep behavior as spawn_creature.
---@param radius number Clamped into [1, find_radius_max] -- note the floor is 1, not 0, unlike the find_* methods.
---@return integer|nil
function api.spawn_creature_near_player(player_id, kind, radius) end

--- Changes one block.
---@param x integer
---@param y integer
---@param z integer
---@param kind string A block id from block_kinds (e.g. "air" to clear a block).
---@return boolean
function api.replace_block(x, y, z, kind) end

--- Sets the weather directly, and resets the engine's own random weather timer (so it won't immediately pick something else out from under you).
---@param name string "clear" is also accepted, as an alias for "sunny" (its name before the 5-weather system existed).
---@return nil
function api.set_weather(name) end

--- Shorthand for set_weather("rain").
---@return nil
function api.start_rain() end

--- Shorthand for set_weather("sunny").
---@return nil
function api.stop_rain() end

--- Sets the time of day directly.
---@param t number Wrapped into [0,1) (e.g. -0.25 and 1.25 both become 0.75), same scale as api.time_of_day.
---@return nil
function api.set_time_of_day(t) end

--- Shorthand for set_time_of_day(0.0).
---@return nil
function api.set_time_dawn() end

--- Shorthand for set_time_of_day(0.5) -- sunset, night begins.
---@return nil
function api.set_time_night() end

--- Queues a notification and server log message, emitted only if the callback commits. At most 8 messages per callback, each at most 512 UTF-8 bytes; exceeding either limit aborts execution with an uncatchable budget failure.
---@param message string
---@return nil
function api.broadcast(message) end

--- Grants items straight into a player's Resources inventory (the panel populated by hand-gathering blocks), bypassing the world entirely. Only use this when the request explicitly asks to add to a player's inventory/resources -- for everything else ("add 100 stone", "fill this area with water"), prefer replace_block to place blocks in the world instead.
---@param player_id integer Target player (matches PlayerSnapshot.id).
---@param kind string A block id from block_kinds, but only the ones gatherable by hand (a resource, not e.g. "air" or "water") count -- anything else is rejected.
---@param amount integer Clamped into [0, item_grant_max].
---@return boolean
function api.give_item(player_id, kind, amount) end

--- Atomically remove resources from any connected player's authoritative inventory, including guests. Staged grants/removals and earlier committed callbacks are included; failed callbacks roll back.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean
function api.take_item(player_id, kind, amount) end

--- Read a resource count for any connected player, including guests. Includes staged inventory changes and earlier accepted callbacks.
---@param player_id integer
---@param kind string
---@return integer|nil
function api.get_resource_count(player_id, kind) end

--- Return a detached table mapping all collectible resource IDs to counts, including zeros, for any connected player. Includes staged changes. Editing this table does not modify inventory. Equipment/items outside the resource catalog are not implemented.
---@param player_id integer
---@return table|nil
function api.get_inventory(player_id) end

--- Whether a connected player holds at least amount of a collectible resource. Amount defaults to 1 when omitted. To check absence use api.has_resource(id, kind) == false; nil means invalid input, not absence.
---@param player_id integer
---@param kind string
---@param amount integer Positive minimum count; default 1.
---@return boolean|nil
function api.has_resource(player_id, kind, amount) end

--- Alias of has_resource for the current resource inventory. No separate equipment-item system exists. Omitted amount defaults to 1; compare result to false to check absence without confusing nil with empty inventory.
---@param player_id integer
---@param kind string
---@param amount integer
---@return boolean|nil
function api.has_item(player_id, kind, amount) end

--- Reduces a player's health, clamped at 0 -- there is no death/respawn system yet, so health just stops there.
---@param player_id integer
---@param amount number
---@return boolean
function api.damage_player(player_id, amount) end

--- Restores a player's health, clamped at 100 (max_health).
---@param player_id integer
---@param amount number
---@return boolean
function api.heal_player(player_id, amount) end

--- Sets a player's poisoned flag directly -- true starts the 1-health-per-poison_tick_secs drain (see PlayerSnapshot.poisoned), false stops it (the hook a future medication item/effect would call; nothing in the engine calls this with false on its own yet).
---@param player_id integer
---@param poisoned boolean
---@return boolean
function api.set_poisoned(player_id, poisoned) end

--- Sets a player's speed_multiplier (applied to their base walk/sprint speed).
---@param player_id integer
---@param multiplier number Clamped into [attribute_multiplier_min, attribute_multiplier_max].
---@return boolean
function api.set_player_speed(player_id, multiplier) end

--- Sets a player's jump_multiplier (applied to their base jump speed).
---@param player_id integer
---@param multiplier number Clamped into [attribute_multiplier_min, attribute_multiplier_max].
---@return boolean
function api.set_player_jump(player_id, multiplier) end

--- Moves a player straight to a position, bypassing normal movement and collision entirely (the same way replace_block bypasses mining). Resets that player's velocity to zero, so they don't keep carrying whatever momentum they had right before the jump.
---@param player_id integer
---@param x number
---@param y number
---@param z number
---@return boolean
function api.teleport_player(player_id, x, y, z) end

--- Called ~10/sec while the module is enabled. Defines a RULE module.
--- Required unless the module defines on_cast instead (exactly one of the two).
---@param api WorldApi
function on_tick(api) end

--- Runs once, immediately, when the host clicks Run. Defines an INSTANT SPELL
--- module instead of a RULE -- mutually exclusive with on_tick.
---@param api WorldApi
---@param event CastEvent
function on_cast(api, event) end

--- Fires once per creature death. Optional.
---@param api WorldApi
---@param event DeathEvent
function on_death(api, event) end

--- Fires once per real player-caused block break. Optional.
---@param api WorldApi
---@param event BlockBreakEvent
function on_block_break(api, event) end

--- Fires once per real player-caused interact-key press (E), never changing
--- the block. Optional.
---@param api WorldApi
---@param event InteractEvent
function on_interact(api, event) end

