// Generated by tools/build_atlas.py from textures/blocks.csv -- do not
// edit by hand. Re-run the script after changing the CSV or textures.

pub const ATLAS_COLS: u32 = 8;
pub const ATLAS_ROWS: u32 = 4;

pub const TILE_BASALT_SIDE: u8 = 0;
pub const TILE_BASALT_TOP: u8 = 1;
pub const TILE_BEDROCK: u8 = 2;
pub const TILE_BIRCH_LEAVES: u8 = 3;
pub const TILE_BIRCH_LOG: u8 = 4;
pub const TILE_BIRCH_LOG_TOP: u8 = 5;
pub const TILE_BRICKS: u8 = 6;
pub const TILE_CHERRY_LEAVES: u8 = 7;
pub const TILE_CHERRY_LOG: u8 = 8;
pub const TILE_CHERRY_LOG_TOP: u8 = 9;
pub const TILE_COBBLESTONE: u8 = 10;
pub const TILE_COPPER_ORE: u8 = 11;
pub const TILE_DIAMOND_ORE: u8 = 12;
pub const TILE_EMERALD_ORE: u8 = 13;
pub const TILE_GOLD_ORE: u8 = 14;
pub const TILE_GRASS: u8 = 15;
pub const TILE_GRASS_BLOCK_SIDE: u8 = 16;
pub const TILE_OAK_LEAVES: u8 = 17;
pub const TILE_OAK_LOG: u8 = 18;
pub const TILE_OAK_LOG_TOP: u8 = 19;
pub const TILE_PUMPKIN_SIDE: u8 = 20;
pub const TILE_PUMPKIN_TOP: u8 = 21;
pub const TILE_SAND: u8 = 22;
pub const TILE_SHORT_GRASS: u8 = 23;
pub const TILE_SOIL: u8 = 24;
pub const TILE_SPRUCE_LEAVES: u8 = 25;
pub const TILE_SPRUCE_LOG: u8 = 26;
pub const TILE_SPRUCE_LOG_TOP: u8 = 27;
pub const TILE_STONE: u8 = 28;
pub const TILE_WATER: u8 = 29;
pub const TILE_PLACEHOLDER: u8 = 30;
pub const TILE_WHITE: u8 = 31;
