// Generated by tools/build_resources.py.
&[
    SurfaceResource { block: BlockType::Fern, habitat: "shade", chance: 0.09, salt: 0x73003768 },
    SurfaceResource { block: BlockType::Clover, habitat: "meadow", chance: 0.025, salt: 0x7300382d },
    SurfaceResource { block: BlockType::Lavender, habitat: "meadow", chance: 0.015, salt: 0x730038f2 },
    SurfaceResource { block: BlockType::RedPoppy, habitat: "meadow", chance: 0.012, salt: 0x730039b7 },
    SurfaceResource { block: BlockType::Bluebell, habitat: "shade", chance: 0.065, salt: 0x73003a7c },
    SurfaceResource { block: BlockType::Cattail, habitat: "wet", chance: 0.055, salt: 0x73003b41 },
    SurfaceResource { block: BlockType::BrownMushroom, habitat: "shade", chance: 0.07, salt: 0x73003c06 },
    SurfaceResource { block: BlockType::Glowcap, habitat: "shade", chance: 0.025, salt: 0x73003ccb },
    SurfaceResource { block: BlockType::ThornBush, habitat: "meadow", chance: 0.014, salt: 0x73003d90 },
    SurfaceResource { block: BlockType::DryShrub, habitat: "dry", chance: 0.04, salt: 0x73003e55 },
]
